### ISSUE TITLE
Formatting of dates in sequence ids

### ISSUE THREAD

**Issue by ekankaka** [PoonLab/bayroot#21]
Hi Art. Had difficulty calling the **get.dates** function.  Can be problematic especially if there are multiple underscores "**_**" in the sequence ids, and if date format is not properly specified. This needs to be emphasized in the README file.

**Comment by ArtPoon** [comment]
Hi @ekankaka - I'm so sorry it took me this long to get to addressing these issues!  I will start working on them now
